# Framework for running automated tests on OSB using Travis-CI, see https://github.com/OpenSourceBrain/osb-model-validation

dist: xenial

addons:
  apt:
    packages:
    - python-matplotlib 
    - python-tk
    - python-numpy 
    - python-scipy 
    - python-lxml
    - python-tornado
    - python-tables

language: python
python: 3.6


env:
    - OMV_ENGINE=NetPyNE
    - OMV_ENGINE=jNeuroML
    - OMV_ENGINE=jNeuroML_NEURON
    - OMV_ENGINE=jNeuroML_NetPyNE
    - OMV_ENGINE=jNeuroML_validate

install: 
    - pip install git+https://github.com/OpenSourceBrain/osb-model-validation

script:
    - omv all -V
    - omv list -V 
    


