#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/usr/arch/nrn"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/usr/arch/nrn/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/u/salvadord/Documents/ISB/Models/M1NetworkModel/sim/x86_64/.libs/libnrnmech.so" "$@"
